version: "3.8"

services:
  learningsystem:
    container_name: learningsystem
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: learningsystem
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
