version: "3.8"

services:
  learningsystem:
    container_name: learningsystem
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: learningsystem
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d

  # section:
  #   build:
  #     context: ./Microservice/section
  #     dockerfile: Dockerfile
  #   image: leemin/section:latest
  #   restart: always
  #   networks:
  #     - playfoo
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #   - "5002:5002"
