version: "3.8"

services:
  CourseMaterials:
    container_name: CourseMaterials
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: CourseMaterials
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - ./CourseMaterialsDB:/docker-entrypoint-initdb.d
